//! `ssk.d/<identity>.conf` (generated from recorded deployments) and the single
//! `Include` line ssk adds to the top of `~/.ssh/config`. Nothing the user wrote is
//! ever modified; the Include is prepended and the rest is preserved byte for byte.

use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use crate::fsx;
use crate::settings;
use crate::state::Deployment;

pub const HEADER: &str =
    "# Generated by ssk. Do not edit: this file is rewritten on every `ssk copy`.\n";

/// `~/.ssh` when the dir is under $HOME (dotfiles-friendly), else the absolute path.
pub fn display_dir(ssh_dir: &Path) -> String {
    display_dir_with(ssh_dir, settings::home_dir().as_deref())
}

pub fn display_dir_with(ssh_dir: &Path, home: Option<&Path>) -> String {
    if let Some(home) = home
        && let Ok(rest) = ssh_dir.strip_prefix(home)
    {
        return format!("~/{}", rest.display());
    }
    ssh_dir.display().to_string()
}

pub fn include_line(ssh_dir: &Path) -> String {
    format!("Include {}/ssk.d/*.conf", display_dir(ssh_dir))
}

pub fn has_include(ssh_dir: &Path) -> io::Result<bool> {
    let want = include_line(ssh_dir);
    match fs::read_to_string(ssh_dir.join("config")) {
        Ok(text) => Ok(text.lines().any(|l| l.trim() == want)),
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(false),
        Err(e) => Err(e),
    }
}

/// Put the Include line first in `config`. Returns true if the file was changed.
pub fn ensure_include(ssh_dir: &Path) -> io::Result<bool> {
    if has_include(ssh_dir)? {
        return Ok(false);
    }
    fsx::ensure_private_dir(ssh_dir)?;
    let path = ssh_dir.join("config");
    let existing = match fs::read_to_string(&path) {
        Ok(t) => t,
        Err(e) if e.kind() == io::ErrorKind::NotFound => String::new(),
        Err(e) => return Err(e),
    };
    let line = include_line(ssh_dir);
    let new = if existing.is_empty() {
        format!("{line}\n")
    } else {
        format!("{line}\n\n{existing}")
    };
    if path.is_symlink() {
        // A dotfiles symlink: write through it rather than replacing it with a plain file.
        fs::write(&path, new)?;
    } else {
        fsx::write_private(&path, new.as_bytes())?;
    }
    Ok(true)
}

pub fn render_conf(ssh_dir: &Path, identity: &str, deployments: &[Deployment]) -> String {
    render_conf_with(&display_dir(ssh_dir), identity, deployments)
}

pub fn render_conf_with(dir_display: &str, identity: &str, deployments: &[Deployment]) -> String {
    let mut s = String::from(HEADER);
    for d in deployments {
        s.push('\n');
        let _ = writeln!(s, "Host {}", d.alias);
        if d.alias != d.host {
            let _ = writeln!(s, "    HostName {}", d.host);
        }
        if let Some(u) = &d.user {
            let _ = writeln!(s, "    User {u}");
        }
        if d.port != 22 {
            let _ = writeln!(s, "    Port {}", d.port);
        }
        let _ = writeln!(s, "    IdentityFile {dir_display}/{identity}");
        let _ = writeln!(s, "    IdentitiesOnly yes");
    }
    s
}

pub fn conf_path(ssh_dir: &Path, identity: &str) -> PathBuf {
    ssh_dir.join("ssk.d").join(format!("{identity}.conf"))
}

pub fn write_conf(
    ssh_dir: &Path,
    identity: &str,
    deployments: &[Deployment],
) -> io::Result<PathBuf> {
    fsx::ensure_private_dir(&ssh_dir.join("ssk.d"))?;
    let path = conf_path(ssh_dir, identity);
    fsx::write_private(
        &path,
        render_conf(ssh_dir, identity, deployments).as_bytes(),
    )?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::Path;

    fn dep(host: &str, user: Option<&str>, port: u16, alias: &str) -> Deployment {
        Deployment {
            host: host.into(),
            user: user.map(String::from),
            port,
            alias: alias.into(),
            installed: "t".into(),
        }
    }

    #[test]
    fn display_dir_prefers_tilde_under_home() {
        assert_eq!(
            display_dir_with(Path::new("/home/j/.ssh"), Some(Path::new("/home/j"))),
            "~/.ssh"
        );
        assert_eq!(
            display_dir_with(Path::new("/srv/keys"), Some(Path::new("/home/j"))),
            "/srv/keys"
        );
        assert_eq!(display_dir_with(Path::new("/srv/keys"), None), "/srv/keys");
    }

    #[test]
    fn renders_blocks_exactly() {
        let deps = vec![
            dep("10.0.0.5", Some("deploy"), 2222, "prod1"),
            dep("git.example", None, 22, "git.example"),
        ];
        let got = render_conf_with("~/.ssh", "work", &deps);
        let want = [
            HEADER.trim_end(),
            "",
            "Host prod1",
            "    HostName 10.0.0.5",
            "    User deploy",
            "    Port 2222",
            "    IdentityFile ~/.ssh/work",
            "    IdentitiesOnly yes",
            "",
            "Host git.example",
            "    IdentityFile ~/.ssh/work",
            "    IdentitiesOnly yes",
            "",
        ]
        .join("\n");
        assert_eq!(got, want);
    }

    #[test]
    fn ensure_include_creates_prepends_and_is_idempotent() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path();
        assert!(ensure_include(dir).unwrap());
        let cfg = dir.join("config");
        assert_eq!(
            fs::read_to_string(&cfg).unwrap(),
            format!("{}\n", include_line(dir))
        );
        assert_eq!(crate::fsx::mode_of(&cfg).unwrap(), 0o600);
        assert!(has_include(dir).unwrap());
        assert!(!ensure_include(dir).unwrap());

        fs::write(&cfg, "Host *\n    ServerAliveInterval 30\n").unwrap();
        assert!(!has_include(dir).unwrap());
        assert!(ensure_include(dir).unwrap());
        assert_eq!(
            fs::read_to_string(&cfg).unwrap(),
            format!(
                "{}\n\nHost *\n    ServerAliveInterval 30\n",
                include_line(dir)
            )
        );
    }

    #[test]
    fn ensure_include_writes_through_a_symlinked_config() {
        let tmp = tempfile::tempdir().unwrap();
        let real = tmp.path().join("dotfiles-config");
        fs::write(&real, "Host x\n").unwrap();
        let dir = tmp.path().join("ssh");
        fs::create_dir(&dir).unwrap();
        std::os::unix::fs::symlink(&real, dir.join("config")).unwrap();
        assert!(ensure_include(&dir).unwrap());
        assert!(dir.join("config").is_symlink(), "symlink must survive");
        assert!(fs::read_to_string(&real).unwrap().starts_with("Include "));
    }

    #[test]
    fn write_conf_creates_sskd_and_file_with_private_modes() {
        let tmp = tempfile::tempdir().unwrap();
        let path = write_conf(tmp.path(), "work", &[dep("h", None, 22, "h")]).unwrap();
        assert_eq!(path, conf_path(tmp.path(), "work"));
        assert_eq!(
            crate::fsx::mode_of(&tmp.path().join("ssk.d")).unwrap(),
            0o700
        );
        assert_eq!(crate::fsx::mode_of(&path).unwrap(), 0o600);
        let text = fs::read_to_string(&path).unwrap();
        assert!(text.starts_with(HEADER));
        assert!(text.contains("Host h\n"));
        assert!(text.contains("IdentitiesOnly yes\n"));
    }
}
